version: '3.1'

services:
  obitem:
    image: obitem
    ports:
      - 8081:8081
    environment:
      SPRING_DATA_MONGODB_HOST: mongo 
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: item-service-db 
      SPRING_DATA_MONGODB_USERNAME: mariem
      SPRING_DATA_MONGODB_PASSWORD: 28360788
  mongo:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mariem
      MONGO_INITDB_ROOT_PASSWORD: 28360788

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mariem
      ME_CONFIG_MONGODB_ADMINPASSWORD: 28360788
      ME_CONFIG_MONGODB_URL: mongodb://mariem:28360788@mongo:27017/


